[package]
name = "handtux"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.0"
image = "0.24.9"
kalosm-ocr = "0.4.0"
lazy_static = "1.5.0"
pyo3 = "0.23.4"
tch = "0.19.0"
tokio = {version = "1.43.0", features = ["full"]}
